#ifndef CONFIG_H
#define CONFIG_H

/*
 * Single source of default configuration.
 * - Edit values in this file.
 * - Reflash to apply firmware defaults.
 */

#define CONFIG_IGNORE_RANGE 0U

#define CONFIG_PASSWORD_LEN 7U
#define CONFIG_LCD_COLS 16U
#define CONFIG_LCD_NORMAL_MOUNT 0U
#define CONFIG_PASSWORD_COL 3U
#define CONFIG_COUNTDOWN_MS 40000U
#define CONFIG_ARM_DELAY_MS 800U

#define CONFIG_ARM_PRESET_ENABLE 0U
#define CONFIG_ARM_PRESET_PASSWORD "7355608"
#define CONFIG_ARM_ERROR_HINT_ENABLE 0U

#define CONFIG_DEFUSE_ENABLE_PASSWORD 0U
#define CONFIG_DEFUSE_ENABLE_MANUAL 1U
#define CONFIG_DEFUSE_ENABLE_EXTERNAL 1U

#define CONFIG_LCD_BACKLIGHT_PCT 50U

#define CONFIG_BEEP_LEN_MS 125U
#define CONFIG_BEEP_INTERVAL_BASE_MS 100U
#define CONFIG_BEEP_INTERVAL_SCALE_MS 900U
#define CONFIG_BEEP_INTERVAL_MIN_MS 150U
#define CONFIG_BEEP_INITIAL_MS 1000U

#define CONFIG_LED_PWM_MAX 1000U
#define CONFIG_LED_BREATH_PERIOD_MS 700U
#define CONFIG_LED_YELLOW_RED_PCT 40U

#define CONFIG_SCROLL_INTERVAL_MS 50U
#define CONFIG_SCROLL_PATTERN_LEN 3U
#define CONFIG_DIGITAL_COUNTDOWN_ENABLE 0U

#define CONFIG_LONG_PRESS_MS 200U
#define CONFIG_MANUAL_DEFUSE_MS 10000U
#define CONFIG_EXTERNAL_DEFUSE_MS 5000U
#define CONFIG_DEFUSE_DISPLAY_HOLD_MS 1200U
#define CONFIG_DEFUSE_CYCLE_STEPS 10U

#define CONFIG_DEFUSE_FLASH_TOGGLE_MS 10U
#define CONFIG_DEFUSE_FLASH_TOGGLES 8U
#define CONFIG_DEFUSE_BLINK_MS 400U

#define CONFIG_BUZZER_STARTUP_FREQ_HZ 4250U
#define CONFIG_BUZZER_COUNTDOWN_FREQ_HZ 3600U
#define CONFIG_BUZZER_DUTY_PCT 50U
#define CONFIG_STARTUP_BEEP_ON_MS 50U
#define CONFIG_STARTUP_BEEP_GAP_MS 50U
#define CONFIG_STARTUP_BEEP_ENABLE 1U

#define CONFIG_MP3_VOLUME 25U
#define CONFIG_MP3_ARM_SUCCESS_ENABLE 1U
#define CONFIG_MP3_DEFUSE_SUCCESS_ENABLE 1U

#define CONFIG_MP3_TRACK_ARM_SUCCESS 101U
#define CONFIG_MP3_TRACK_EXPLOSION 102U
#define CONFIG_MP3_TRACK_DEFUSE_SUCCESS 103U
#define CONFIG_MP3_TRACK_CTWIN 104U
#define CONFIG_MP3_TRACK_TERWIN 105U

#define CONFIG_MP3_DEFUSE_STAGE_ENABLE 1U
#define CONFIG_MP3_EXPLODED_STAGE_ENABLE 1U

#define CONFIG_MP3_EXPLOSION_ENABLE 1U
#define CONFIG_MP3_CT_WIN_MUSICBOX_ENABLE 1U
#define CONFIG_MP3_T_WIN_MUSICBOX_ENABLE 1U
#define CONFIG_MP3_CTWIN_ENABLE 1U
#define CONFIG_MP3_TERWIN_ENABLE 1U

#define CONFIG_MP3_CT_WIN_MUSICBOX_TRACK 10U
#define CONFIG_MP3_T_WIN_MUSICBOX_TRACK 1U

#define CONFIG_MP3_DEFUSE_SUCCESS_WAIT_MS 2700U
#define CONFIG_MP3_CT_MUSICBOX_WAIT_MS 9000U
#define CONFIG_MP3_T_MUSICBOX_WAIT_MS 10000U
#define CONFIG_MP3_EXPLOSION_ONLY_WAIT_MS 7000U

#define CONFIG_EXPLOSION_BEEP_MS 500U

#define CONFIG_RESET_MAGIC 90405U
#define CONFIG_RESET_CODE "090405"

#include "config_range.h"

#endif
